server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param

spring:
  application:
    name: erp

  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@localhost:1521/orclpdb}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: America/Guatemala

logging:
  level:
    root: INFO
    com.umg.seguridad: DEBUG
    org.springframework.jdbc.core: DEBUG


security:
  jwt:
    secret-key: CAMBIA_ESTO_POR_UNA_CLAVE_LARGA_Y_SEGURA_1234567890
    expiration-ms: 3600000